export const PROJECTS = [
  {
    id: "EduNext",
    featured: true,
    category: "Full Stack",
    year: "2024",
    title: "Fikiara — Online Learning Platform",
    description: "A full-stack learning platform where instructors publish structured courses and students track lesson-by-lesson progress.",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Node.js"],
    links: { caseStudy: "#", liveDemo: "#", github: "#" },
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=2000",
  },
  {
    id: "nexus",
    featured: false,
    category: "Dashboard",
    year: "2024",
    title: "Nexus Admin — Analytics & Role-Based Dashboard",
    description: "An admin dashboard with data tables, charts, permissions and audit-friendly activity views, built as a reusable foundation.",
    tags: ["React", "TypeScript", "Tailwind CSS", "Recharts"],
    links: { caseStudy: "#", liveDemo: "#", github: "#" },
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1000",
  },
  {
    id: "kravu",
    featured: false,
    category: "E-commerce",
    year: "2024",
    title: "Kravu Store — Modern E-commerce Experience",
    description: "A storefront covering catalogue browsing, cart, checkout and order history with a clean, conversion-focused product flow.",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Node.js"],
    links: { caseStudy: "#", liveDemo: "#", github: "#" },
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=1000",
  },
  {
    id: "practi",
    featured: false,
    category: "Full Stack",
    year: "2024",
    title: "Practi — Practitioner Booking SaaS",
    description: "A scheduling application where practitioners manage availability and clients book confirmed slots without back-and-forth messaging.",
    tags: ["Next.js", "TypeScript", "Node.js"],
    links: { caseStudy: "#", liveDemo: "#", github: "#" },
    image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=1000",
  },
  {
    id: "aura",
    featured: false,
    category: "Business",
    year: "2024",
    title: "Aura Interiors — Studio Business Website",
    description: "A fast, editorial marketing site for a design studio, built for lead capture and strong search visibility.",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    links: { caseStudy: "#", liveDemo: "#", github: "#" },
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1000",
  },
  {
    id: "apilab",
    featured: false,
    category: "Frontend",
    year: "2024",
    title: "API Lab — Request & Response Playground",
    description: "An experimental in-browser client for exploring REST endpoints, inspecting responses and saving request collections.",
    tags: ["React", "TypeScript", "Tailwind CSS"],
    links: { caseStudy: "#", liveDemo: "#", github: "#" },
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=1000",
  },
];
